// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {radikron} from '../models';

export function FetchProgramSnapshots():Promise<void>;

export function GetAvailableStations():Promise<Array<string>>;

export function GetConfig():Promise<config.Config>;

export function GetConfigFile():Promise<string>;

export function GetMonitoringStatus():Promise<boolean>;

export function GetSchedules():Promise<radikron.Progs>;

export function LoadConfig(arg1:string):Promise<void>;

export function OpenDirectory(arg1:string):Promise<void>;

export function SaveConfig(arg1:string):Promise<void>;

export function SearchWeeklyPrograms(arg1:string,arg2:string,arg3:string,arg4:string):Promise<radikron.Progs>;

export function StartMonitoring():Promise<void>;

export function StopMonitoring():Promise<void>;

export function UpdateConfig(arg1:config.Config):Promise<void>;
