// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableStations() {
  return window['go']['main']['App']['GetAvailableStations']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigFile() {
  return window['go']['main']['App']['GetConfigFile']();
}

export function GetMonitoringStatus() {
  return window['go']['main']['App']['GetMonitoringStatus']();
}

export function LoadConfig(arg1) {
  return window['go']['main']['App']['LoadConfig'](arg1);
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SearchWeeklyPrograms(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchWeeklyPrograms'](arg1, arg2, arg3, arg4);
}

export function StartMonitoring() {
  return window['go']['main']['App']['StartMonitoring']();
}

export function StopMonitoring() {
  return window['go']['main']['App']['StopMonitoring']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
