// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetAvailableStations():Promise<Array<string>>;

export function GetConfig():Promise<config.Config>;

export function GetMonitoringStatus():Promise<boolean>;

export function LoadConfig(arg1:string):Promise<void>;

export function SaveConfig(arg1:string):Promise<void>;

export function StartMonitoring():Promise<void>;

export function StopMonitoring():Promise<void>;
