// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {radikron} from '../models';

export function DeleteManualInjection(arg1:string):Promise<void>;

export function ExportConfigFile():Promise<void>;

export function FetchProgramSnapshots():Promise<void>;

export function GetAllStations():Promise<Array<string>>;

export function GetAvailableStations():Promise<Array<string>>;

export function GetConfig():Promise<config.Config>;

export function GetConfigFile():Promise<string>;

export function GetDesignatedFolder(arg1:radikron.Prog,arg2:string,arg3:string):Promise<string>;

export function GetMonitoringStatus():Promise<boolean>;

export function GetSchedules():Promise<radikron.Progs>;

export function HandleDownloadCompleted(arg1:string,arg2:string,arg3:string):Promise<void>;

export function HandleDownloadCompletedByID(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function InjectProgram(arg1:radikron.Prog,arg2:string):Promise<void>;

export function IsManualInjection(arg1:string):Promise<boolean>;

export function LoadConfig(arg1:string):Promise<void>;

export function OpenDirectory(arg1:string):Promise<void>;

export function ReadConfigFile():Promise<string>;

export function SaveConfig(arg1:string):Promise<void>;

export function SearchWeeklyPrograms(arg1:string,arg2:string,arg3:string,arg4:string):Promise<radikron.Progs>;

export function SelectDirectory():Promise<string>;

export function StartMonitoring():Promise<void>;

export function StopMonitoring():Promise<void>;

export function UpdateConfig(arg1:config.Config):Promise<void>;
