// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteManualInjection(arg1) {
  return window['go']['main']['App']['DeleteManualInjection'](arg1);
}

export function ExportConfigFile() {
  return window['go']['main']['App']['ExportConfigFile']();
}

export function FetchProgramSnapshots() {
  return window['go']['main']['App']['FetchProgramSnapshots']();
}

export function GetAllStations() {
  return window['go']['main']['App']['GetAllStations']();
}

export function GetAvailableStations() {
  return window['go']['main']['App']['GetAvailableStations']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigFile() {
  return window['go']['main']['App']['GetConfigFile']();
}

export function GetDesignatedFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDesignatedFolder'](arg1, arg2, arg3);
}

export function GetMonitoringStatus() {
  return window['go']['main']['App']['GetMonitoringStatus']();
}

export function GetSchedules() {
  return window['go']['main']['App']['GetSchedules']();
}

export function HandleDownloadCompleted(arg1, arg2, arg3) {
  return window['go']['main']['App']['HandleDownloadCompleted'](arg1, arg2, arg3);
}

export function HandleDownloadCompletedByID(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['HandleDownloadCompletedByID'](arg1, arg2, arg3, arg4);
}

export function InjectProgram(arg1, arg2) {
  return window['go']['main']['App']['InjectProgram'](arg1, arg2);
}

export function IsManualInjection(arg1) {
  return window['go']['main']['App']['IsManualInjection'](arg1);
}

export function LoadConfig(arg1) {
  return window['go']['main']['App']['LoadConfig'](arg1);
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function ReadConfigFile() {
  return window['go']['main']['App']['ReadConfigFile']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SearchWeeklyPrograms(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchWeeklyPrograms'](arg1, arg2, arg3, arg4);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartMonitoring() {
  return window['go']['main']['App']['StartMonitoring']();
}

export function StopMonitoring() {
  return window['go']['main']['App']['StopMonitoring']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
